#!/bin/python3

import sys

def solve(n, s, d, m):
    # Complete this function
    output=0
    for i in range(n):
        if i < n:
            if sum(s[i:i+m])==d:
                #a = sum(s[i:i+m])
                #print(a)
                output+=1
    return(output)
n = int(input().strip())
s = list(map(int, input().strip().split(' ')))
d, m = input().strip().split(' ')
d, m = [int(d), int(m)]
result = solve(n, s, d, m)
print(result)
