#!/bin/python3

import sys

def catAndMouse(x, y, z):
    # Complete this function
    a = "Cat A"
    b = "Cat B"
    c = "Mouse C"
    if abs(x-z) > abs(y-z):
        return(b)
    elif abs(y-z)>abs(x-z):
        return(a)
    else:
        return(c)

if __name__ == "__main__":
    q = int(input().strip())
    for a0 in range(q):
        x, y, z = input().strip().split(' ')
        x, y, z = [int(x), int(y), int(z)]
        result = catAndMouse(x, y, z)
        print(result)
        #print (" ".join(map(str, result)))


