#!/bin/python3

import sys

def solve(year):
    if year == 1918:
        date="26.09."+str(year)
        return(date)
    if year > 1917 and year%4==0 and year%100!=0 or year%400==0:
        date = "12.09." + str(year)
        return(date)
    if year > 1917 and year%4!=0 and year%100==0 or year%400!=0:
        date = "13.09."+str(year)
        return(date)
    if year > 1917 and year%4!=0: 
        date = "13.09."+ str(year)
        return(date)
    if year <=1917 and year%4!=0:
        date = "31.08."+str(year)
        return(date)
    if year < 1917 and year%4==0:
        date="30.08."+str(year)
        return(date)
    
        
        
    

year = int(input().strip())
result = solve(year)
print(result)
