#!/bin/python3

import sys

def divisibleSumPairs(n, k, ar):
    # Complete this function
    output=0
    if n == len(ar): 
        for i in range(len(ar)):
            for j in range(len(ar)):
                if i < j:
                    if (ar[i]+ar[j])%k==0:
                        output+=1
    return(output)

n, k = input().strip().split(' ')
n, k = [int(n), int(k)]
ar = list(map(int, input().strip().split(' ')))
result = divisibleSumPairs(n, k, ar)
print(result)
