#!/bin/python3

import sys

def solve(n, p):
    # Complete this function
    return(min(p//2, n//2 - p//2))
#    turns = []
#    num_turns =0
#    back_turns=0
#    a = n-p
#    b =p-1
#    if b < a:  
#        for i in range(1,n,2):
#           if p-1<=i:
#                num_turns+=1
#                turns.append(num_turns)
#    else:
#        if n%2!=0 and n-p==1:
#            return(0)
#        else:
#            for i in range(n,0,-1):
#                if p-1>=i:
#                    back_turns+=1
#                    turn.append(back_turns)
#    return(min(turns))
n = int(input().strip())
p = int(input().strip())
result = solve(n, p)
print(result)
