#!/bin/python3

import sys

def extraLongFactorials(n):
    # Complete this function
    product=1
    for i in range(n):
        product = product*(i+1)
    print(product)
if __name__ == "__main__":
    n = int(input().strip())
    extraLongFactorials(n)
